local function shoot(self)
	local pos = go.get_position()
	pos.z = 0.1 

	factory.create("#bullet_factory", pos, nil, { direction = self.shoot_dir })
end

function init(self)
	msg.post(".", "acquire_input_focus")
	self.input = vmath.vector3()
	self.speed = 400
	self.shoot_dir = vmath.vector3(0, 1, 0)

	timer.delay(0.3, true, function()
		shoot(self)
	end)
end

function update(self, dt)
	if vmath.length_sqr(self.input) > 0 then
		self.input = vmath.normalize(self.input)
		local pos = go.get_position()
		go.set_position(pos + self.input * self.speed * dt)
		self.input = vmath.vector3()
	end
end

function on_input(self, action_id, action)
	if action_id == hash("touch") or action_id == hash("click") then
		if action.pressed or action.repeated then
			local touch_pos = vmath.vector3(action.x, action.y, 0)
			local player_pos = go.get_position()
			local diff = touch_pos - player_pos
			if vmath.length(diff) > 10 then 
				self.input = vmath.normalize(diff)
			end
		end
	elseif action_id == hash("up") then
		self.input.y = 1
	elseif action_id == hash("down") then
		self.input.y = -1
	elseif action_id == hash("left") then
		self.input.x = -1
	elseif action_id == hash("right") then
		self.input.x = 1
	end
end